# @usage
# on:
#   pull_request:
#     types: [opened]
# jobs:
#   add-assignee-to-pr:
#     uses: route06/actions/.github/workflows/_add-assignee-to-pr.yml@v1
on:
  workflow_call:

jobs:
  add-assignee-to-pr:
    name: Add assignee to PR
    runs-on: ubuntu-latest
    timeout-minutes: 1

    if: ${{ github.event.pull_request.user.type != 'Bot' && toJSON(github.event.pull_request.assignees) == '[]' }}

    steps:
      - uses: technote-space/assign-author@v1
