# PR 作成時に assignee を、PR 作成者に設定する。ただし、以下のケースを除く。
#   * PR 作成者のユーザータイプが Bot である
#   * すでに PR 作成時に assignee が設定されている
#
# @usage
# on:
#   pull_request:
#     types: [opened]
# jobs:
#   add-assignee-to-pr:
#     uses: route06/actions/.github/workflows/add_assignee_to_pr.yml@v2
on:
  workflow_call:

jobs:
  add-assignee-to-pr:
    name: Add assignee to PR
    runs-on: ubuntu-latest
    timeout-minutes: 1

    if: ${{ github.event.pull_request.user.type != 'Bot' && toJSON(github.event.pull_request.assignees) == '[]' }}

    steps:
      - uses: technote-space/assign-author@v1
