# @usage
#
# name: Create discussion
#
# on:
#   schedule:
#     # 毎週水曜 13:00 JST に実行
#     - cron: "0 4 * * wed"
#

name: Get next date

on:
  workflow_call:
    inputs: 
      target_schedule:
        description: daily, weekly, monthly, yearlyのいずれかを指定してください。
        default: weekly
        type: string
      target_day:
        description: 週次の場合の対象曜日を指定してください。
        default: monday
        type: string
      target_date:
        description: 月次の場合の対象日を指定してください。
        default: "1"
        type: string
      target_yearly_date:
        description: 年次の場合の対象月日を指定してください。
        default: 01-01
        type: string
      time_zone:
        description: タイムゾーンを指定してください。
        default: "Asia/Tokyo"
        type: string
    outputs:
      next_date:
        description: yyyy/mm/dd形式で日付を返します。
        value: ${{ jobs.get_next_schedule_date.outputs.next_date }}

jobs:
  get_next_schedule_date:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: ${{ inputs.time_zone }}
    steps:
      - name: Run script
        id: get_date
        run: |
            if [ "${{ inputs.target_schedule }}" = "daily" ]; then
                next_date=$(date -d "tomorrow" +%Y/%m/%d)
            elif [ "${{ inputs.target_schedule }}" = "weekly" ]; then
                next_date=$(date -d "next ${{ inputs.target_day }}" +%Y/%m/%d)
            elif [ "${{ inputs.target_schedule }}" = "monthly" ]; then
                today=$(date +%d)
                if [ "$today" -lt "${{ inputs.target_date }}" ]; then
                  next_date=$(date -d "$(date +%Y-%m-)${{ inputs.target_date }}" +%Y/%m/%d)
                else
                  next_date=$(date -d "$(date +%Y-%m-01) +1 month +$((inputs.target_date-1)) days" +%Y/%m/%d)
                fi
            elif [ "${{ inputs.target_schedule }}" = "yearly" ]; then
                current_year=$(date +%Y)
                current_month_day=$(date +%m-%d)
                if [ "$current_month_day" = "${{ inputs.target_yearly_date }}" ]; then
                  next_date=$(date -d "$current_year-${{ inputs.target_yearly_date }} +1 year" +%Y/%m/%d)
                else
                  if [ "$current_month_day" -lt "${{ inputs.target_yearly_date }}" ]; then
                      next_date=$(date -d "$current_year-${{ inputs.target_yearly_date }}" +%Y/%m/%d)
                  else
                      next_date=$(date -d "$((current_year + 1))-${{inputs.target_yearly_date }}" +%Y/%m/%d)
                  fi
                fi
            else
                echo "Invalid TARGET_SCHEDULE value"
                exit 1
            fi
            echo "next_date=$next_date" >> "$GITHUB_OUTPUT"
    outputs:
        next_date: ${{ steps.get_date.outputs.next_date }}