# ## Summary
#
# Create GitHub Issue from the given arguments.

# ## Usage
#
# name: Create GitHub Issue
#
# on:
#   schedule:
#     # 毎週水曜 13:00 JST に実行
#     - cron: "0 4 * * wed"
#
# jobs:
#   create_discussion:
#     uses: route06/actions/.github/workflows/create_gh_issue.yml@v2
#     permissions:
#       contents: read
#       issues: write
#     with:
#       title: Sample Issue
#       description_template_path: _templates/sample_issue.md
#       assignees: alice, bob
#       labels: bug, wontfix

name: Create GitHub Issue

on:
  workflow_call:
    inputs:
      title:
        description: "作成する Issue のタイトル"
        required: true
        type: string
      description_template_path:
        description: "Issue の説明に利用するテンプレートファイルのパス"
        required: true
        type: string
      assignees:
        description: "（任意）Issue の Assignees; 例: alice, bob"
        type: string
      labels:
        description: "（任意）Issue の Labels; 例: bug, wontfix"
        type: string
    outputs:
      number:
        description: "作成された Issue Number"
        value: ${{ jobs.create_issue.outputs.number }}
      url:
        description: "作成された Issue URL"
        value: ${{ jobs.create_issue.outputs.url }}

jobs:
  create_issue:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      LABELS: "${{ inputs.labels }}"
    steps:
      - uses: actions/checkout@v4
      - name: Decide template filename
        run: |
          echo "TEMPLATE_WITH_HEADER=template_work$$.md" >> "$GITHUB_ENV"
      - name: Setup issue template
        run: |
          echo ""

          cat <<EOF > ${{ env.TEMPLATE_WITH_HEADER }}
          ---
          title: "${{ inputs.title }}"
          assignees: "${{ inputs.assignees }}"
          labels: "${{ inputs.labels }}"
          ---

          $(cat ${{ inputs.description_template_path }})
          EOF
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        id: create_an_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ${{ env.TEMPLATE_WITH_HEADER }}
    outputs:
      number: ${{ steps.create_an_issue.outputs.number }}
      url: ${{ steps.create_an_issue.outputs.url }}
