# "SLACK_WEBHOOK_URL" に紐づく channel に、CI 失敗時用の Slack 通知をする。"title" を設定可能。
#
# @usage
#
# jobs:
#   notify:
#     uses: route06/actions/.github/workflows/notify_slack_on_ci_failed.yml@v2
#     with:
#       title: CI failed / ci.yml
#     secrets:
#       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_XXX_WEBHOOK_URL }}
on:
  workflow_call:
    inputs:
      title:
        description: Slackメッセージのタイトル
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify-slack-on-ci-failed:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set COMMIT_MESSAGE
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" | tr '\n' ' ' >> "$GITHUB_ENV"
      - name: Notify to slack
        uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf # v1.3.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ${{ inputs.title }}
          attachments: |
            [
              {
                "color": "bad",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ env.COMMIT_MESSAGE }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "title": "Compare URL",
                    "value": "${{ github.event.compare }}"
                  }
                ]
              }
            ]
