name: Setup PR

on:
  pull_request:

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add-assignee-to-pr:
    uses: ./.github/workflows/_add-assignee-to-pr.yml
